### ISSUE TITLE
Attachments not converting on custom objects?

### ISSUE THREAD

**Issue by melsherm3** [DouglasCAyers/sfdc-convert-attachments-to-chatter-files#11]
Hi,

Thanks for posting this! I ran it in my sandbox and it worked great for my standard objects, but attachments were not converted to files for my custom objects. Any idea why that might happen? I enabled convert if feed tracking is disabled and confirmed that the attachments are not private. 

Melissa

**Comment by DouglasCAyers** [comment]
Hi Melissa,

Glad it worked for you (somewhat)! Thanks for clarifying that it does work for your standard objects and what options you have enabled.

Some questions to help troubleshoot:
* Did you receive any error emails or do you see any error messages in the Debug Logs when you run conversion for the custom objects? To receive a success/error email you may need to set the custom setting `Convert_Attachments_to_Files_Settings__c.Conversion_Result_Email_Notifications__c` to your email address.
* Are the owners of the attachments **active** users?
* Did you set the custom setting `Convert_Attachments_to_Files_Settings__c.Convert_in_Near_Real_Time__c` to true? The Attachment trigger looks for that value to be true to enqueue the conversion job otherwise waits for you to manually perform the conversion by executing the batch job.
*  You mention you enabled "convert if feed tracking is disabled", if indeed the custom objects do not have Feed Tracking enabled then the files will only appear in the Chatter Files tab, they won't have been shared to the records and displayed in the Files related list. Can you confirm how you were testing that the files were converted?
* What volume of attachments are you trying to convert? Do note there is a 36,000 limit of ContentVersions that can be created in a 24/hour period.

Thanks,

Doug

**Comment by melsherm3** [comment]
Thanks for the help! The owners weren't active, so I'll try again with
active owners.

Melissa

**Comment by DouglasCAyers** [comment]
Hi Melissa,

Did trying with active owners resolve your issue?

Thanks,

Doug

**Comment by melsherm3** [comment]
Yes it did. Thanks for your help!

Melissa
