### ISSUE TITLE
Insert failed. First exception on row 0; first error: REQUIRED_FIELD_MISSING, Required fields are missing: [File_Type__c]: [File_Type__c] Edit Summary: Item 3

### ISSUE THREAD

**Issue by jangenc** [DouglasCAyers/sfdc-convert-attachments-to-chatter-files#25]
Hi,

I have a question concerning your tool.
We created a new object and transferred al the notes and attachments from the old opportunities object to a new custom object. But they are only visible in Notes and Attachments and I wanted to use your tool to transfer all these attachements to Files.

But when I am doin this I always receive this error 
_Insert failed. First exception on row 0; first error: REQUIRED_FIELD_MISSING, Required fields are missing: [File_Type__c]: [File_Type__c]
Edit Summary: Item 3
_

Do you have any Idea?

Many thanks!

Kind Regards,
Jan

**Comment by DouglasCAyers** [comment]
Hi Jan,

Is that error being reported in the conversion log object?

If yes I'm guessing your org has a custom field on Content Version object named File_Type__c, and that field is marked as required?

If yes then you can either modify the code (if you install directly from GitHub instead of managed package) such that when the ContentVersion is created you populate the custom field, or you can mark that custom field as not required. 

Doug

**Comment by DouglasCAyers** [comment]
Hi @jangenc,

I never got a reply regarding your issue. My guess it was due to custom validation rules or a custom field that was marked required on `ContentVersion` object. I'm going to close this issue but if you encounter another problem please open a new issue on GitHub for me to investigate.

Thanks,

Doug
