### ISSUE TITLE
Missing Organization Feature: EnhancedEmail

### ISSUE THREAD

**Issue by unidha** [DouglasCAyers/sfdc-convert-attachments-to-chatter-files#35]
My organization enable Email to Case. Previously we successfully installed the package but now it asking for EnhancedEmail  to be enabled.

**Comment by DouglasCAyers** [comment]
Hi @unidha,

Yes, the conversion tool requires **Enhanced Email** feature enabled because the code has checks to avoid trying to convert attachments belonging to `EmailMessage` object.

Probably not the best solution in place as there are other objects that have to be checked like `EmailTemplate` and `Solution` which don't seem to support Files either. You can track progress towards a new feature to let admins configure which parent object types should have attachments converted at https://github.com/DouglasCAyers/sfdc-convert-attachments-to-chatter-files/issues/15

Thanks,

Doug
